### ISSUE TITLE
search_resultのエラーハンドリング

### ISSUE THREAD

**Issue by noimin0610** [jphacks/SD_1705#30]
server😄つ🐛 😡💢front
APIから返されるstatusに応じてfrontにエラーを返す

**Comment by noimin0610** [comment]
OK, NOT_FOUND, ZERO_RESULTS, UNKNOWN_ERRORの扱い
NOT_FOUNDなら，frontにdictを返す
ZERO_RESULTSなら，ルートがないことをfrontに送る
UNKNOWN_ERRORなら，もう一回まわす

**Comment by noimin0610** [comment]
OK, NOT_FOUND, ZERO_RESULTS, UNKNOWN_ERRORの扱い
NOT_FOUNDなら，frontにdictを返す
ZERO_RESULTSなら，ルートがないことをfrontに送る
UNKNOWN_ERRORなら，もう一回まわす(MAX回数越えたらエラーを吐く)

NOT_FOUNT, ZERO_RESULTS, UNKNOWN_ERRORの場合はstatus[0]でステータス(NOT_FOUNT, ZERO_RESULTS, UNKNOWN_ERRORのいずれか)が取れます。NOT_FOUNT, ZERO_RESULTSの場合，status[1]にdictが入っています。

**Comment by noimin0610** [comment]
sessionでdictを返すように情報の渡し方を変更

**Comment by nkiyuu** [comment]
- NOT_FOUND : {original: '東京', dist: '仙台', way0:False}
- ZERO_RESULTS: boolean
- UNKNOWN_ERROR: boolean

**Comment by noimin0610** [comment]
- NOT_FOUND : {original: '東京', dist: '仙台', way0:None}
- ZERO_RESULTS: boolean
- UNKNOWN_ERROR: boolean
