### ISSUE TITLE
search_resultの検索オプション

### ISSUE THREAD

**Issue by yayamochi** [jphacks/SD_1705#47]
## 欲しい機能
- ジャンルを入れる
- 取得半径
- 移動の手段

これを私が頑張ります( ∩'-'⊂ )

**Comment by nkiyuu** [comment]
サーバの実装がまだ

**Comment by yayamochi** [comment]
- googlemapももっかい呼び出すかも
- 高速道路とかの呼び出しもやるから〜

**Comment by noimin0610** [comment]
交通手段の選択肢は
- 車
- 徒歩
- 自転車
- 公共交通機関
の4パターンでお願いします

**Comment by noimin0610** [comment]
Hotpeperに存在するジャンル一覧
居酒屋
ダイニングバー
創作料理
和食
洋食
イタリアン・フレンチ
中華
焼肉・韓国料理
アジアン
各国料理
カラオケ・パーティ
バー・カクテル
ラーメン
お好み焼き・もんじゃ・鉄板焼き
カフェ・スイーツ
その他グルメ
