### ISSUE TITLE
ファボ切り替えの通知と更新

### ISSUE THREAD

**Issue by yayamochi** [jphacks/SD_1705#58]

**Comment by nkiyuu** [comment]
フロント -> サーバ
GET /fav/:store_id

**Comment by yayamochi** [comment]
レストランテーブルはファボが来たら登録するから
全部GETで送る

**Comment by noimin0610** [comment]
URLにstore_idを含める必要がなくなったので/fav/:store_idではなく/favで

**Comment by noimin0610** [comment]
GETじゃなくてPOSTにします
