### ISSUE TITLE
レストランモデル作る

### ISSUE THREAD

**Issue by nkiyuu** [jphacks/SD_1705#6]

**Comment by noimin0610** [comment]
各店舗について最低限欲しい情報
- id
- 緯度経度
- 店名
- 住所
- 予算
- 営業時間
- 駐車場の有無
- ホットペッパーのページのURL

メソッドについて
__repr__では上3つが欲しいです
1店舗の上記の情報を全部dictかなんかで返してくれるメソッドも欲しいです
あと他に欲しくなったら追加で書きます
