### ISSUE TITLE
表示されるmapとサーバ側で検索しているmapがずれている問題

### ISSUE THREAD

**Issue by taku-ito** [jphacks/SD_1705#71]
* JS側をDrivingにしてもルートが変わらない？

**Comment by taku-ito** [comment]
* JS側のapiではなぜか高速を通らない？？？
* 現在，高速を通る場合でもその高速道路の架橋した等のお店は表示されている

**Comment by taku-ito** [comment]
サーバ側でAPIを叩かずに，JS側で叩いたほうがいい？

**Comment by nkiyuu** [comment]
js側でapi叩くときは徒歩固定になっているからだと思う  
そこはすぐに変えられるはず

js側で全てやろうと思ったとき，サーバで受けとる値が変わるので  
そこらへんは大変なことになりそう

**Comment by taku-ito** [comment]
Drivingにしても，高速道路を走ってくれなかったのですが...
僕のタイプミス？
# テストケース
* 仙台駅 => 前沢駅

**Comment by nkiyuu** [comment]
交通手段が変わらないところが問題
って認識で合ってる？

**Comment by taku-ito** [comment]
現状として，交通手段がちゃんと変わっているのか確認ができていないです．
ですが，DRIVINGに変えても徒歩のままになっている可能性が高いです

  var request = {
    origin:org,
    destination:des,
    waypoints: waypts,
    travelMode: google.maps.DirectionsTravelMode.DRIVING
  }

でいいのかと思っていたのですが...

**Comment by nkiyuu** [comment]
https://github.com/jphacks/SD_1705/pull/73

交通手段変わらない問題対応しました  
確認してみてください

**Comment by nkiyuu** [comment]
この問題根が深そうだな・・・
